# SPDX-License-Identifier: BUSL-1.1
# Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four
# years from publication; Change License: Apache-2.0
# Copyright (c) 2026 Empower Agile
"""Rendering contract of the generated ``glossary.md`` review surface."""

from __future__ import annotations

from datetime import date

import pytest
from narrativetrace_glossary import (
    BoundedContext,
    Glossary,
    GlossaryTerm,
    SynonymAlias,
    TermKind,
    TermStatus,
    render_glossary_markdown,
)

FIRST_SEEN = date(2026, 8, 11)

PREAMBLE = [
    "# Domain Glossary",
    "",
    "Generated from `glossary.json` — edit the JSON, then regenerate; do not edit this file.",
]

TABLE_HEADER = [
    "| Term | Status | Definition | Deprecated synonyms | Translations |",
    "|---|---|---|---|---|",
]


def document(*lines: str) -> str:
    return "\n".join([*PREAMBLE, *lines]) + "\n"


def term(text: str, context: str = "billing", **overrides: object) -> GlossaryTerm:
    fields: dict[str, object] = {
        "term": text,
        "context": context,
        "kind": TermKind.NOUN_PHRASE,
        "status": TermStatus.HARVESTED,
        "first_seen": FIRST_SEEN,
    }
    fields.update(overrides)
    return GlossaryTerm(**fields)  # type: ignore[arg-type]


def one_context(*terms: GlossaryTerm) -> Glossary:
    return Glossary({"billing": BoundedContext("billing")}, list(terms))


ABBREVIATIONS_INTRO = (
    "Shorthand this project has accepted. Clarity scoring reads these as the project's own words "
    "instead of asking for them to be spelled out."
)


def test_an_empty_glossary_renders_only_the_preamble() -> None:
    assert render_glossary_markdown(Glossary()) == document()


def test_accepted_abbreviations_render_as_a_list_before_the_contexts() -> None:
    glossary = Glossary(
        {"billing": BoundedContext("billing")},
        abbreviations={"fx": "foreign exchange", "calc": "calculate"},
    )

    assert render_glossary_markdown(glossary) == document(
        "",
        "## Accepted abbreviations",
        "",
        ABBREVIATIONS_INTRO,
        "",
        "- `calc` — calculate",
        "- `fx` — foreign exchange",
        "",
        "## billing",
    )


def test_a_glossary_without_abbreviations_renders_no_such_section() -> None:
    assert "Accepted abbreviations" not in render_glossary_markdown(one_context(term("invoice")))


def test_an_abbreviation_expansion_spanning_lines_collapses_onto_one_line() -> None:
    glossary = Glossary(abbreviations={"fx": "foreign\nexchange"})

    assert "- `fx` — foreign exchange\n" in render_glossary_markdown(glossary)


def test_the_canonical_sample_renders_context_prose_then_one_table_per_kind(
    populated_glossary: Glossary,
) -> None:
    row = (
        "| overdraft account | curated "
        "| Account permitted to go below zero up to an agreed limit. "
        "| account with overdraft — legacy v1 API phrasing "
        "| es: cuenta con descubierto |"
    )

    assert render_glossary_markdown(populated_glossary) == document(
        "",
        "## _unassigned",
        "",
        "## billing",
        "",
        "Charging, invoicing, funds",
        "",
        "Packages: `acme.billing`",
        "",
        "### Noun phrases",
        "",
        *TABLE_HEADER,
        row,
    )


def test_contexts_render_sorted_by_name_whatever_order_they_were_declared_in() -> None:
    declared = Glossary(
        {name: BoundedContext(name) for name in ("shipping", "_unassigned", "billing")}
    )

    rendered = [
        line for line in render_glossary_markdown(declared).splitlines() if line[:3] == "## "
    ]

    assert rendered == ["## _unassigned", "## billing", "## shipping"]


def test_kind_tables_render_in_grammatical_order_and_skip_kinds_with_no_terms() -> None:
    glossary = one_context(
        term("place order", kind=TermKind.VERB_PHRASE),
        term("invoice", kind=TermKind.WORD),
    )

    headings = [
        line for line in render_glossary_markdown(glossary).splitlines() if line[:4] == "### "
    ]

    assert headings == ["### Words", "### Verb phrases"]


def test_every_kind_has_a_heading_of_its_own() -> None:
    glossary = one_context(
        term("invoice", kind=TermKind.WORD),
        term("overdraft account", kind=TermKind.NOUN_PHRASE),
        term("place order", kind=TermKind.VERB_PHRASE),
        term("charged {amount}", kind=TermKind.TEMPLATE),
    )

    headings = [
        line for line in render_glossary_markdown(glossary).splitlines() if line[:4] == "### "
    ]

    assert headings == ["### Words", "### Noun phrases", "### Verb phrases", "### Templates"]


def test_a_term_with_no_curated_content_renders_empty_cells() -> None:
    rendered = render_glossary_markdown(one_context(term("invoice")))

    assert "| invoice | harvested |  |  |  |" in rendered


def test_translations_render_sorted_by_locale() -> None:
    entry = term("invoice", translations={"pt": "fatura", "es": "factura", "de": "Rechnung"})

    rendered = render_glossary_markdown(one_context(entry))

    assert "| de: Rechnung; es: factura; pt: fatura |" in rendered


def test_several_synonyms_render_separated_and_annotated() -> None:
    entry = term(
        "overdraft account",
        synonyms=[SynonymAlias("account with overdraft", "legacy v1"), SynonymAlias("od account")],
    )

    rendered = render_glossary_markdown(one_context(entry))

    assert "| account with overdraft — legacy v1; od account |" in rendered


def test_a_pipe_in_curated_text_is_escaped_so_it_cannot_split_the_row() -> None:
    entry = term("invoice", definition="a | b", synonyms=[SynonymAlias("x | y")])

    rendered = render_glossary_markdown(one_context(entry))

    assert r"| invoice | harvested | a \| b | x \| y |  |" in rendered


@pytest.mark.parametrize("line_break", ["\n", "\r\n", "\r"])
def test_a_line_break_in_curated_text_collapses_to_a_space(line_break: str) -> None:
    entry = term("invoice", definition=f"first{line_break}second")

    rendered = render_glossary_markdown(one_context(entry))

    assert "| invoice | harvested | first second |  |  |" in rendered


def test_a_context_description_renders_above_its_tables() -> None:
    glossary = Glossary({"billing": BoundedContext("billing", [], "Charging and invoicing")})

    assert render_glossary_markdown(glossary) == document(
        "", "## billing", "", "Charging and invoicing"
    )


def test_several_declared_prefixes_render_as_one_inline_code_list() -> None:
    glossary = Glossary({"billing": BoundedContext("billing", ["acme.billing", "acme.invoicing"])})

    assert "Packages: `acme.billing`, `acme.invoicing`" in render_glossary_markdown(glossary)


def test_the_document_always_ends_with_a_newline() -> None:
    assert render_glossary_markdown(one_context(term("invoice"))).endswith(" |\n")


def test_rendering_rejects_a_missing_glossary() -> None:
    with pytest.raises(TypeError, match=r"\Aglossary must be a Glossary\Z"):
        render_glossary_markdown(None)  # type: ignore[arg-type]
