# SPDX-License-Identifier: BUSL-1.1
# Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four
# years from publication; Change License: Apache-2.0
# Copyright (c) 2026 Empower Agile
"""Renders the generated ``glossary.md`` view of a glossary.

``GlossaryMarkdownRenderer``. The Markdown view is the PR-review surface (ADR-011): one
section per context, one table per term kind, definitions/synonyms/translations inline. It is
regenerated on every harvest and never edited — the JSON is the single editable source.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence

from narrativetrace_glossary.models import (
    BoundedContext,
    Glossary,
    GlossaryTerm,
    TermKind,
)

_PREAMBLE = (
    "# Domain Glossary\n\n"
    "Generated from `glossary.json` — edit the JSON, then regenerate; do not edit this file.\n"
)

_ABBREVIATIONS_SECTION = (
    "\n## Accepted abbreviations\n\n"
    "Shorthand this project has accepted. Clarity scoring reads these as the project's own words "
    "instead of asking for them to be spelled out.\n\n"
)

_TABLE_HEADER = (
    "| Term | Status | Definition | Deprecated synonyms | Translations |\n|---|---|---|---|---|\n"
)

_KIND_HEADINGS = {
    TermKind.WORD: "Words",
    TermKind.NOUN_PHRASE: "Noun phrases",
    TermKind.VERB_PHRASE: "Verb phrases",
    TermKind.TEMPLATE: "Templates",
}


def _inline(text: str) -> str:
    """Collapses line breaks so one value stays one Markdown line."""
    return text.replace("\r\n", " ").replace("\n", " ").replace("\r", " ")


def _cell(text: str) -> str:
    """Escapes table-breaking characters: pipes are escaped, line breaks collapse to spaces."""
    return _inline(text.replace("|", r"\|"))


def _render_abbreviations(abbreviations: Mapping[str, str]) -> str:
    """Renders accepted shorthand as a list, sorted; empty when the project declared none.

    A list rather than a table: the section is a flat repository-wide map, and keeping it out of
    the table grammar means an abbreviation containing a pipe needs no escaping to stay readable.
    """
    if not abbreviations:
        return ""
    entries = "".join(
        f"- `{_inline(abbreviation)}` — {_inline(abbreviations[abbreviation])}\n"
        for abbreviation in sorted(abbreviations)
    )
    return _ABBREVIATIONS_SECTION + entries


def _synonyms_cell(term: GlossaryTerm) -> str:
    return "; ".join(
        _cell(synonym.alias)
        if synonym.note is None
        else f"{_cell(synonym.alias)} — {_cell(synonym.note)}"
        for synonym in term.synonyms
    )


def _translations_cell(term: GlossaryTerm) -> str:
    return "; ".join(
        f"{_cell(locale)}: {_cell(term.translations[locale])}"
        for locale in sorted(term.translations)
    )


def _render_row(term: GlossaryTerm) -> str:
    definition = "" if term.definition is None else _cell(term.definition)
    return (
        f"| {_cell(term.term)} | {term.status.value} | {definition} "
        f"| {_synonyms_cell(term)} | {_translations_cell(term)} |\n"
    )


def _render_kind_table(terms: Sequence[GlossaryTerm], kind: TermKind) -> str:
    if not terms:
        return ""
    rows = "".join(_render_row(term) for term in terms)
    return f"\n### {_KIND_HEADINGS[kind]}\n\n{_TABLE_HEADER}{rows}"


def _terms_of(glossary: Glossary, context: str, kind: TermKind) -> list[GlossaryTerm]:
    return [term for term in glossary.terms if term.context == context and term.kind is kind]


def _render_prose(context: BoundedContext) -> str:
    prose = f"\n## {_cell(context.name)}\n"
    if context.description is not None:
        prose += f"\n{context.description}\n"
    if context.packages:
        declared = ", ".join(f"`{prefix}`" for prefix in context.packages)
        prose += f"\nPackages: {declared}\n"
    return prose


def _render_context(glossary: Glossary, context: BoundedContext) -> str:
    tables = "".join(
        _render_kind_table(_terms_of(glossary, context.name, kind), kind) for kind in TermKind
    )
    return _render_prose(context) + tables


def render_glossary_markdown(glossary: Glossary) -> str:
    """Renders the full Markdown document: accepted abbreviations, then contexts sorted by name.

    The abbreviations section leads because it is repository-wide rather than scoped to a context,
    and because the reviewable document has to show the vocabulary decision it exists to show.
    """
    if not isinstance(glossary, Glossary):
        raise TypeError("glossary must be a Glossary")
    sections = "".join(
        _render_context(glossary, glossary.contexts[name]) for name in sorted(glossary.contexts)
    )
    document = _PREAMBLE + _render_abbreviations(glossary.abbreviations) + sections
    assert document.endswith("\n"), "document must end with a newline"
    return document
