# SPDX-License-Identifier: BUSL-1.1
# Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four
# years from publication; Change License: Apache-2.0
# Copyright (c) 2026 Empower Agile
"""The report every feedback test starts from, and a one-field override.

Shaped after ``tests/doctor/conftest.py``'s snapshot factory: a case says what is DIFFERENT about
it, so a test reads as the one decision it is about rather than as eight constructor arguments.

**@llmNote** :func:`doctor_report_json` does not CONTAIN a doctor report — it runs the real doctor
over a real snapshot and renders the real JSON. Java's own helper hand-wrote one, PARAPHRASED
``trap.redaction-proof``'s message, and the paraphrase is why 654 green tests never noticed that the
gate refused every doctor report there is: the paraphrase had no redaction marker in it, and the
marker is the whole defect. Cross-port item 2 asks for a test asserting the hand-written stand-in
still carries the generator's own bytes; generating it instead means there is no stand-in to drift.
:class:`TestTheDoctorReportIsTheRealGeneratedArtifact` in ``test_value_free_check.py`` pins that the
generated text really does quote the marker, so the premise of the exemption cannot quietly stop
being true.
"""

from __future__ import annotations

from typing import Any

from narrativetrace_tooling.doctor.doctor import run_doctor
from narrativetrace_tooling.doctor.render import render_json
from narrativetrace_tooling.doctor.types import DoctorSnapshot
from narrativetrace_tooling.feedback.report import (
    AgentIdentity,
    Attachments,
    FeedbackCategory,
    FeedbackReport,
    ProblemNarrative,
)

STRUCTURAL_TRACE = """scenario: Order is placed

- OrderService.place_order(customer_id, total)
  - Inventory.reserve(sku) → value
"""
"""One structural trace, in this runtime's own ``.nt`` grammar (two-space indent per depth)."""


def doctor_snapshot() -> DoctorSnapshot:
    """A project the doctor can read: enough for every check to reach a verdict, and nothing that
    would make one of them raise."""
    return DoctorSnapshot(
        cwd="/project",
        python_version="3.12.4",
        env={},
        root_pyproject={"project": {"name": "orders", "dependencies": ["narrativetrace"]}},
        narrativetrace_config={},
        source_files={"tests/test_orders.py": "def test_orders() -> None:\n    assert True\n"},
    )


def doctor_report_json() -> str:
    """The doctor's own ``--json`` report for :func:`doctor_snapshot`, generated by the real
    doctor — the bytes a drafted report actually attaches."""
    return render_json(run_doctor(doctor_snapshot()))


def a_report(**overrides: Any) -> FeedbackReport:
    """One complete, value-free report, with any field overridden by name.

    A case says what is DIFFERENT about it, so a test reads as the one decision it is about rather
    than as eight constructor arguments. Overrides are applied to the ARGUMENTS, not through
    ``with_fields``, so a test can hand in a value the constructor must refuse.
    """
    arguments: dict[str, Any] = {
        "runtime": "python",
        "category": FeedbackCategory.DOCTOR,
        "install": "narrativetrace==0.2.0, narrativetrace-pytest==0.2.0",
        "step": "trap.redaction-proof",
        "narrative": ProblemNarrative(
            "ran the doctor, applied the fix it printed, ran it again",
            "the same check still failed, with the same message",
            "the check to pass once the test asserts the marker",
        ),
        "language": "en",
        "agent": AgentIdentity("example-cli", "example-model"),
        "attachments": Attachments.of(doctor_report_json(), STRUCTURAL_TRACE),
    }
    arguments.update(overrides)
    return FeedbackReport(**arguments)
