# SPDX-License-Identifier: BUSL-1.1
# Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four
# years from publication; Change License: Apache-2.0
# Copyright (c) 2026 Empower Agile
"""Generated data (byte-identical to Java AbbreviationDictionary). Do not edit by hand."""

# abbreviation -> (tier, expansion)
ABBREVIATIONS = {
    "id": ("UNIVERSAL", "identifier"),
    "url": ("UNIVERSAL", "uniform resource locator"),
    "uri": ("UNIVERSAL", "uniform resource identifier"),
    "api": ("UNIVERSAL", "application programming interface"),
    "html": ("UNIVERSAL", "hypertext markup language"),
    "xml": ("UNIVERSAL", "extensible markup language"),
    "json": ("UNIVERSAL", "javascript object notation"),
    "http": ("UNIVERSAL", "hypertext transfer protocol"),
    "https": ("UNIVERSAL", "hypertext transfer protocol secure"),
    "db": ("UNIVERSAL", "database"),
    "io": ("UNIVERSAL", "input output"),
    "ui": ("UNIVERSAL", "user interface"),
    "ok": ("UNIVERSAL", "okay"),
    "max": ("UNIVERSAL", "maximum"),
    "min": ("UNIVERSAL", "minimum"),
    "sql": ("UNIVERSAL", "structured query language"),
    "css": ("UNIVERSAL", "cascading style sheets"),
    "tcp": ("UNIVERSAL", "transmission control protocol"),
    "udp": ("UNIVERSAL", "user datagram protocol"),
    "ip": ("UNIVERSAL", "internet protocol"),
    "dns": ("UNIVERSAL", "domain name system"),
    "ssh": ("UNIVERSAL", "secure shell"),
    "ssl": ("UNIVERSAL", "secure sockets layer"),
    "tls": ("UNIVERSAL", "transport layer security"),
    "jwt": ("UNIVERSAL", "json web token"),
    "cpu": ("UNIVERSAL", "central processing unit"),
    "gpu": ("UNIVERSAL", "graphics processing unit"),
    "ram": ("UNIVERSAL", "random access memory"),
    "os": ("UNIVERSAL", "operating system"),
    "jvm": ("UNIVERSAL", "java virtual machine"),
    "gc": ("UNIVERSAL", "garbage collector"),
    "uuid": ("UNIVERSAL", "universally unique identifier"),
    "sdk": ("UNIVERSAL", "software development kit"),
    "grpc": ("UNIVERSAL", "grpc remote procedure calls"),
    "sso": ("UNIVERSAL", "single sign on"),
    "mfa": ("UNIVERSAL", "multi factor authentication"),
    "pii": ("UNIVERSAL", "personally identifiable information"),
    "kpi": ("UNIVERSAL", "key performance indicator"),
    "ctx": ("WELL_KNOWN", "context"),
    "cfg": ("WELL_KNOWN", "configuration"),
    "config": ("WELL_KNOWN", "configuration"),
    "mgr": ("WELL_KNOWN", "manager"),
    "impl": ("WELL_KNOWN", "implementation"),
    "src": ("WELL_KNOWN", "source"),
    "dest": ("WELL_KNOWN", "destination"),
    "dst": ("WELL_KNOWN", "destination"),
    "buf": ("WELL_KNOWN", "buffer"),
    "idx": ("WELL_KNOWN", "index"),
    "tmp": ("WELL_KNOWN", "temporary"),
    "temp": ("WELL_KNOWN", "temporary"),
    "auth": ("WELL_KNOWN", "authentication"),
    "repo": ("WELL_KNOWN", "repository"),
    "env": ("WELL_KNOWN", "environment"),
    "async": ("WELL_KNOWN", "asynchronous"),
    "sync": ("WELL_KNOWN", "synchronous"),
    "param": ("WELL_KNOWN", "parameter"),
    "params": ("WELL_KNOWN", "parameters"),
    "attr": ("WELL_KNOWN", "attribute"),
    "attrs": ("WELL_KNOWN", "attributes"),
    "ref": ("WELL_KNOWN", "reference"),
    "conn": ("WELL_KNOWN", "connection"),
    "stmt": ("WELL_KNOWN", "statement"),
    "msg": ("WELL_KNOWN", "message"),
    "req": ("WELL_KNOWN", "request"),
    "res": ("WELL_KNOWN", "response"),
    "resp": ("WELL_KNOWN", "response"),
    "err": ("WELL_KNOWN", "error"),
    "exc": ("WELL_KNOWN", "exception"),
    "ex": ("WELL_KNOWN", "exception"),
    "cmd": ("WELL_KNOWN", "command"),
    "arg": ("WELL_KNOWN", "argument"),
    "args": ("WELL_KNOWN", "arguments"),
    "val": ("WELL_KNOWN", "value"),
    "var": ("WELL_KNOWN", "variable"),
    "vars": ("WELL_KNOWN", "variables"),
    "str": ("WELL_KNOWN", "string"),
    "num": ("WELL_KNOWN", "number"),
    "len": ("WELL_KNOWN", "length"),
    "pos": ("WELL_KNOWN", "position"),
    "prev": ("WELL_KNOWN", "previous"),
    "cur": ("WELL_KNOWN", "current"),
    "curr": ("WELL_KNOWN", "current"),
    "iter": ("WELL_KNOWN", "iterator"),
    "obj": ("WELL_KNOWN", "object"),
    "fn": ("WELL_KNOWN", "function"),
    "func": ("WELL_KNOWN", "function"),
    "cb": ("WELL_KNOWN", "callback"),
    "evt": ("WELL_KNOWN", "event"),
    "elem": ("WELL_KNOWN", "element"),
    "elems": ("WELL_KNOWN", "elements"),
    "prop": ("WELL_KNOWN", "property"),
    "props": ("WELL_KNOWN", "properties"),
    "dir": ("WELL_KNOWN", "directory"),
    "lib": ("WELL_KNOWN", "library"),
    "pkg": ("WELL_KNOWN", "package"),
    "ver": ("WELL_KNOWN", "version"),
    "doc": ("WELL_KNOWN", "document"),
    "docs": ("WELL_KNOWN", "documents"),
    "spec": ("WELL_KNOWN", "specification"),
    "fmt": ("WELL_KNOWN", "format"),
    "seq": ("WELL_KNOWN", "sequence"),
    "init": ("WELL_KNOWN", "initialize"),
    "dyn": ("WELL_KNOWN", "dynamic"),
    "alloc": ("WELL_KNOWN", "allocate"),
    "dealloc": ("WELL_KNOWN", "deallocate"),
    "chan": ("WELL_KNOWN", "channel"),
    "ack": ("WELL_KNOWN", "acknowledge"),
    "nack": ("WELL_KNOWN", "negative acknowledge"),
    "coll": ("WELL_KNOWN", "collection"),
    "desc": ("WELL_KNOWN", "description"),
    "info": ("WELL_KNOWN", "information"),
    "stat": ("WELL_KNOWN", "status"),
    "stats": ("WELL_KNOWN", "statistics"),
    "cnt": ("WELL_KNOWN", "count"),
    "avg": ("WELL_KNOWN", "average"),
    "pct": ("WELL_KNOWN", "percent"),
    "delim": ("WELL_KNOWN", "delimiter"),
    "sep": ("WELL_KNOWN", "separator"),
    "hdr": ("WELL_KNOWN", "header"),
    "svc": ("WELL_KNOWN", "service"),
    "txn": ("WELL_KNOWN", "transaction"),
    "tx": ("WELL_KNOWN", "transaction"),
    "ttl": ("WELL_KNOWN", "time to live"),
    "qps": ("WELL_KNOWN", "queries per second"),
    "rps": ("WELL_KNOWN", "requests per second"),
    "mtls": ("WELL_KNOWN", "mutual transport layer security"),
    "oidc": ("WELL_KNOWN", "openid connect"),
    "sli": ("WELL_KNOWN", "service level indicator"),
    "slo": ("WELL_KNOWN", "service level objective"),
    "sla": ("WELL_KNOWN", "service level agreement"),
    "etl": ("WELL_KNOWN", "extract transform load"),
    "elt": ("WELL_KNOWN", "extract load transform"),
    "cdc": ("WELL_KNOWN", "change data capture"),
    "oltp": ("WELL_KNOWN", "online transaction processing"),
    "olap": ("WELL_KNOWN", "online analytical processing"),
    "p99": ("WELL_KNOWN", "99th percentile"),
    "llm": ("WELL_KNOWN", "large language model"),
    "asr": ("WELL_KNOWN", "automatic speech recognition"),
    "tts": ("WELL_KNOWN", "text to speech"),
    "ner": ("WELL_KNOWN", "named entity recognition"),
    "ocr": ("WELL_KNOWN", "optical character recognition"),
    "totp": ("WELL_KNOWN", "time based one time password"),
    "siem": ("WELL_KNOWN", "security information and event management"),
    "soc2": ("WELL_KNOWN", "service organization control 2"),
    "gdpr": ("WELL_KNOWN", "general data protection regulation"),
    "hipaa": ("WELL_KNOWN", "health insurance portability and accountability act"),
    "cust": ("AMBIGUOUS", "customer or custom"),
    "proc": ("AMBIGUOUS", "process"),
    "mod": ("AMBIGUOUS", "module or modifier"),
    "del": ("AMBIGUOUS", "delete or delegate"),
    "acc": ("AMBIGUOUS", "account or accumulator"),
    "op": ("AMBIGUOUS", "operation or operator"),
    "rec": ("AMBIGUOUS", "record or receiver"),
    "sec": ("AMBIGUOUS", "section or security or second"),
    "gen": ("AMBIGUOUS", "generate or generic or generation"),
    "app": ("AMBIGUOUS", "application or append"),
    "calc": ("AMBIGUOUS", "calculate or calculation"),
    "cat": ("AMBIGUOUS", "category or concatenate"),
    "comp": ("AMBIGUOUS", "compare or component or compute"),
    "loc": ("AMBIGUOUS", "location or locale"),
    "perm": ("AMBIGUOUS", "permission or permanent"),
    "reg": ("AMBIGUOUS", "register or regular or registry"),
    "srv": ("AMBIGUOUS", "server or service"),
    "tgt": ("AMBIGUOUS", "target"),
    "hdl": ("AMBIGUOUS", "handle or handler"),
    "blk": ("AMBIGUOUS", "block"),
    "chk": ("AMBIGUOUS", "check"),
    "clr": ("AMBIGUOUS", "clear or color"),
    "cmp": ("AMBIGUOUS", "compare or component"),
    "cpy": ("AMBIGUOUS", "copy"),
    "dup": ("AMBIGUOUS", "duplicate"),
    "flt": ("AMBIGUOUS", "filter or float"),
    "grp": ("AMBIGUOUS", "group"),
    "lbl": ("AMBIGUOUS", "label"),
    "lvl": ("AMBIGUOUS", "level"),
    "mgmt": ("AMBIGUOUS", "management"),
    "neg": ("AMBIGUOUS", "negative or negate"),
    "orig": ("AMBIGUOUS", "original or origin"),
    "pfx": ("AMBIGUOUS", "prefix"),
    "sfx": ("AMBIGUOUS", "suffix"),
    "sig": ("AMBIGUOUS", "signal or signature"),
    "sym": ("AMBIGUOUS", "symbol or symmetric"),
    "tbl": ("AMBIGUOUS", "table"),
    "tok": ("AMBIGUOUS", "token"),
    "usr": ("AMBIGUOUS", "user"),
    "wgt": ("AMBIGUOUS", "weight"),
    "rag": ("AMBIGUOUS", "retrieval augmented generation or red amber green"),
}
