# SPDX-License-Identifier: BUSL-1.1
# Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four
# years from publication; Change License: Apache-2.0
# Copyright (c) 2026 Empower Agile
"""Generated data (byte-identical to Java CollocationDictionary). Do not edit by hand."""

# noun -> preferred verbs (union across all domain category maps)
COLLOCATIONS = {
    "account": ("debit", "credit", "balance", "close", "reconcile", "freeze"),
    "ledger": ("reconcile", "balance", "post", "close"),
    "payment": ("authorize", "capture", "disburse", "remit", "settle", "refund", "void"),
    "loan": ("originate", "underwrite", "amortize", "service", "default"),
    "invoice": ("issue", "settle", "void", "dispute"),
    "transaction": ("commit", "rollback", "authorize", "settle", "void", "reverse"),
    "portfolio": ("rebalance", "diversify", "hedge", "liquidate"),
    "bond": ("issue", "mature", "redeem", "yield", "coupon"),
    "tax": ("withhold", "file", "remit", "assess", "levy", "exempt"),
    "budget": ("allocate", "forecast", "reconcile", "approve"),
    "asset": ("value", "revalue", "impair", "liquidate"),
    "collateral": ("pledge", "release", "haircut"),
    "order": ("place", "fulfill", "cancel", "ship", "return", "backorder"),
    "cart": ("add", "remove", "empty", "checkout", "abandon"),
    "inventory": ("replenish", "reserve", "deplete", "count", "restock"),
    "product": ("list", "delist", "discount", "bundle", "feature"),
    "subscription": ("activate", "cancel", "renew", "pause", "upgrade", "downgrade"),
    "coupon": ("apply", "redeem", "expire", "validate"),
    "price": ("set", "reprice", "discount", "markdown"),
    "return": ("authorize", "receive", "refund", "restock"),
    "patient": ("admit", "discharge", "refer", "triage", "diagnose", "treat"),
    "medication": ("prescribe", "administer", "dispense", "discontinue", "titrate"),
    "appointment": ("schedule", "cancel", "reschedule", "confirm", "checkin"),
    "diagnosis": ("confirm", "rule", "differential", "code"),
    "record": ("chart", "amend", "seal", "release"),
    "vaccine": ("administer", "store", "discard"),
    "specimen": ("collect", "label", "process"),
    "reservation": ("book", "confirm", "cancel", "modify", "honor", "overbook"),
    "room": ("assign", "vacate", "upgrade", "block", "service"),
    "guest": ("checkin", "checkout", "accommodate", "bill", "comp"),
    "booking": ("rebook", "confirm", "cancel"),
    "seat": ("assign", "upgrade", "downgrade"),
    "call": ("route", "drop", "forward", "transfer", "mute", "hold", "record"),
    "signal": ("amplify", "attenuate", "modulate", "demodulate", "broadcast"),
    "channel": ("allocate", "multiplex", "tune", "scramble"),
    "subscriber": ("provision", "suspend", "activate", "port", "throttle"),
    "session": ("originate", "terminate", "handoff", "create", "invalidate", "extend", "hijack"),
    "bandwidth": ("allocate", "shape", "throttle"),
    "player": ("spawn", "respawn", "ban", "kick", "matchmake", "rank"),
    "item": ("equip", "loot", "craft", "enchant", "disenchant", "trade"),
    "character": ("level", "buff", "debuff", "heal", "revive", "nerf"),
    "match": ("start", "pause", "forfeit", "abandon", "spectate"),
    "queue": ("join", "leave", "matchmake", "drain", "purge", "park", "resume"),
    "lobby": ("create", "join", "leave"),
    "shipment": ("dispatch", "track", "reroute", "deliver", "return", "insure"),
    "cargo": ("load", "unload", "stow", "manifest", "inspect", "clear"),
    "route": ("plan", "optimize", "divert", "schedule"),
    "container": (
        "load",
        "seal",
        "unseal",
        "transload",
        "build",
        "deploy",
        "kill",
        "restart",
        "orchestrate",
    ),
    "dock": ("assign", "slot", "release"),
    "policy": (
        "underwrite",
        "issue",
        "renew",
        "cancel",
        "lapse",
        "reinstate",
        "endorse",
        "evaluate",
        "enforce",
        "apply",
        "override",
        "simulate",
        "attest",
    ),
    "claim": ("file", "adjust", "settle", "deny", "subrogate", "appeal"),
    "premium": ("quote", "calculate", "collect", "waive", "refund"),
    "endorsement": ("add", "remove", "amend"),
    "deductible": ("apply", "waive"),
    "student": ("enroll", "expel", "graduate", "mentor", "counsel", "assess"),
    "course": ("register", "audit", "drop", "complete", "accredit"),
    "grade": ("assign", "appeal", "curve", "post", "withhold"),
    "attendance": ("record", "audit", "verify"),
    "exam": ("schedule", "proctor", "grade"),
    "property": ("list", "appraise", "inspect", "close", "escrow", "foreclose"),
    "lease": ("sign", "renew", "terminate", "sublease", "amend"),
    "tenant": (
        "screen",
        "evict",
        "accommodate",
        "bill",
        "provision",
        "isolate",
        "migrate",
        "suspend",
        "activate",
        "offboard",
    ),
    "title": ("search", "clear", "record"),
    "showing": ("schedule", "cancel"),
    "employee": ("hire", "onboard", "promote", "demote", "terminate", "furlough", "transfer"),
    "candidate": ("screen", "interview", "recruit", "reject", "shortlist"),
    "position": ("post", "fill", "eliminate", "reclassify"),
    "headcount": ("plan", "reduce", "increase"),
    "compensation": ("benchmark", "adjust", "approve"),
    "token": (
        "issue",
        "revoke",
        "refresh",
        "rotate",
        "invalidate",
        "blacklist",
        "mint",
        "burn",
        "stake",
        "transfer",
        "vest",
        "lock",
    ),
    "credential": ("verify", "revoke", "hash", "store", "rotate"),
    "certificate": ("sign", "revoke", "renew", "chain", "pin"),
    "key": ("generate", "rotate", "revoke", "archive"),
    "acl": ("enforce", "evaluate", "audit"),
    "instance": ("provision", "deploy", "scale", "terminate", "snapshot", "migrate"),
    "pipeline": ("trigger", "run", "abort", "retry", "promote"),
    "cache": ("warm", "invalidate", "evict", "flush", "populate"),
    "node": (
        "cordon",
        "drain",
        "uncordon",
        "create",
        "build",
        "render",
        "visit",
        "traverse",
        "remove",
        "insert",
        "find",
        "update",
        "delete",
    ),
    "release": ("promote", "rollback", "rollout"),
    "dataset": ("ingest", "cleanse", "partition", "sample", "anonymize"),
    "schema": (
        "migrate",
        "validate",
        "version",
        "evolve",
        "normalize",
        "define",
        "generate",
        "infer",
    ),
    "index": ("build", "rebuild", "drop", "optimize", "shard"),
    "query": ("execute", "optimize", "cache", "paginate", "throttle"),
    "feature": ("derive", "normalize", "vectorize"),
    "window": ("slide", "aggregate", "rank"),
    "article": ("draft", "publish", "archive", "retract", "syndicate"),
    "comment": ("post", "moderate", "flag", "delete", "pin"),
    "media": ("upload", "transcode", "stream", "caption", "watermark"),
    "subtitle": ("generate", "sync", "translate"),
    "transcript": ("generate", "edit", "publish"),
    "user": ("follow", "unfollow", "block", "mute", "report", "verify"),
    "post": ("publish", "pin", "boost", "archive", "flag"),
    "thread": ("start", "lock", "archive"),
    "message": (
        "send",
        "delete",
        "unsend",
        "enqueue",
        "dequeue",
        "acknowledge",
        "nack",
        "retry",
        "deadletter",
    ),
    "event": ("emit", "publish", "replay", "fanout", "route", "consume", "handle", "enrich"),
    "device": ("provision", "commission", "decommission", "pair", "unpair", "reboot"),
    "sensor": ("calibrate", "sample", "poll", "stream"),
    "telemetry": ("capture", "ingest", "aggregate"),
    "contract": (
        "draft",
        "sign",
        "amend",
        "terminate",
        "enforce",
        "breach",
        "deploy",
        "verify",
        "audit",
        "upgrade",
        "pause",
    ),
    "case": (
        "file",
        "adjudicate",
        "dismiss",
        "settle",
        "appeal",
        "categorize",
        "prioritize",
        "reopen",
        "resolve",
    ),
    "verdict": ("deliver", "appeal", "overturn", "uphold"),
    "motion": ("file", "argue", "grant", "deny"),
    "brief": ("draft", "file", "amend"),
    "batch": ("start", "inspect", "reject", "release", "quarantine"),
    "component": ("assemble", "solder", "weld", "test", "certify"),
    "line": ("start", "stop", "balance", "retool"),
    "workorder": ("create", "schedule", "close"),
    "field": (
        "plant",
        "irrigate",
        "fertilize",
        "harvest",
        "read",
        "write",
        "map",
        "validate",
        "serialize",
        "redact",
    ),
    "crop": ("sow", "spray", "prune", "harvest"),
    "livestock": ("feed", "breed", "vaccinate", "wean"),
    "campaign": ("launch", "pause", "optimize", "target", "remarket"),
    "audience": ("segment", "target", "exclude", "expand", "suppress"),
    "creative": ("draft", "review", "approve", "rotate"),
    "flight": ("schedule", "delay", "depart", "arrive", "reroute"),
    "vessel": ("berth", "moor", "unmoor", "dock"),
    "vehicle": ("dispatch", "refuel", "reroute", "park"),
    "grid": ("balance", "stabilize", "shed", "curtail", "interconnect"),
    "meter": ("read", "calibrate", "install", "replace", "tamper"),
    "feeder": ("energize", "deenergize", "switch", "island"),
    "plant": ("dispatch", "ramp", "derate", "blackstart"),
    "validator": ("delegate", "redelegate", "slash", "unbond"),
    "bridge": ("lock", "mint", "burn", "release"),
    "permit": ("issue", "renew", "revoke", "approve"),
    "license": ("issue", "renew", "suspend", "revoke"),
    "ordinance": ("draft", "enact", "amend", "repeal"),
    "assay": ("run", "validate", "repeat"),
    "sample": ("aliquot", "dilute", "incubate", "analyze"),
    "compound": ("synthesize", "formulate", "stabilize"),
    "ticket": ("open", "triage", "assign", "escalate", "resolve", "close"),
    "customer": ("notify", "update", "verify", "retain"),
    "payout": ("initiate", "disburse", "settle", "reverse"),
    "chargeback": ("file", "dispute", "win", "lose"),
    "authorization": ("request", "reauthorize", "decline", "approve"),
    "impression": ("serve", "count", "cap", "pace"),
    "bid": ("submit", "win", "lose", "optimize"),
    "tree": ("build", "render", "traverse", "walk", "flatten", "prune", "create", "parse"),
    "list": ("create", "build", "render", "filter", "sort", "append", "remove", "clear", "find"),
    "score": ("compute", "calculate", "normalize", "compare", "update", "aggregate"),
    "value": ("get", "set", "render", "format", "parse", "validate", "compute", "convert"),
    "text": ("render", "format", "parse", "tokenize", "trim", "split", "join", "encode"),
    "name": (
        "parse",
        "validate",
        "format",
        "generate",
        "resolve",
        "normalize",
        "tokenize",
        "score",
    ),
    "error": ("handle", "throw", "catch", "log", "report", "wrap", "format", "recover"),
    "result": ("compute", "build", "format", "render", "aggregate", "merge", "collect"),
    "state": ("update", "reset", "restore", "save", "load", "merge", "initialize", "validate"),
    "context": ("create", "build", "enter", "exit", "restore", "save", "capture", "wrap"),
    "source": ("read", "parse", "scan", "analyze", "load", "validate", "compile", "transform"),
    "parameter": ("validate", "parse", "capture", "render", "extract", "format", "score"),
    "issue": ("collect", "detect", "report", "create", "resolve", "format", "filter"),
    "method": ("score", "analyze", "extract", "invoke", "call", "find", "validate"),
    "class": ("define", "instantiate", "extend", "load", "inspect", "serialize"),
    "object": ("create", "clone", "serialize", "deserialize", "validate", "merge"),
    "module": ("load", "initialize", "configure", "wire", "register", "reload"),
    "package": ("publish", "install", "resolve", "upgrade", "sign", "scan"),
    "exception": ("throw", "catch", "wrap", "propagate", "log", "map"),
    "buffer": ("allocate", "fill", "flush", "drain", "resize", "slice"),
    "stream": ("open", "read", "write", "flush", "close", "pipe"),
    "payload": ("build", "parse", "validate", "sanitize", "sign", "compress"),
    "request": ("build", "send", "retry", "cancel", "validate", "throttle"),
    "response": ("return", "serialize", "parse", "cache", "stream", "validate"),
    "command": ("dispatch", "execute", "validate", "queue", "retry", "cancel"),
    "handler": ("register", "resolve", "invoke", "chain", "decorate", "replace"),
    "factory": ("create", "build", "configure", "wire", "cache", "resolve"),
    "endpoint": ("expose", "secure", "version", "deprecate", "throttle", "document"),
    "webhook": ("register", "deliver", "sign", "verify", "retry", "disable"),
    "gateway": ("route", "authorize", "throttle", "cache", "rewrite"),
    "featureflag": ("enable", "disable", "rollout", "target", "evaluate", "retire"),
    "job": ("schedule", "enqueue", "run", "retry", "cancel", "monitor"),
    "workflow": ("start", "advance", "pause", "resume", "cancel", "complete"),
    "rule": ("define", "evaluate", "prioritize", "enforce", "override", "disable"),
    "template": ("render", "compile", "validate", "version", "override", "publish"),
    "artifact": ("build", "publish", "sign", "promote", "download", "verify"),
    "metric": ("record", "aggregate", "export", "tag", "sample", "reset"),
    "trace": ("start", "annotate", "propagate", "sample", "flush", "end"),
    "span": ("start", "annotate", "tag", "link", "flush", "finish"),
    "alert": ("trigger", "silence", "acknowledge", "escalate", "resolve"),
    "incident": ("declare", "triage", "escalate", "mitigate", "resolve", "postmortem"),
    "dashboard": ("build", "publish", "share", "refresh", "drilldown", "archive"),
    "log": ("write", "parse", "filter", "ship", "redact", "correlate"),
    "checkpoint": ("create", "restore", "persist", "prune", "verify", "rotate"),
    "model": ("train", "validate", "evaluate", "serve", "deploy", "retrain"),
    "embedding": ("generate", "index", "normalize", "store", "cache", "search"),
    "prompt": ("compose", "template", "ground", "evaluate", "sanitize", "version"),
    "classifier": ("train", "score", "calibrate", "threshold", "evaluate", "serve"),
    "prediction": ("generate", "score", "explain", "cache", "serve", "audit"),
    "experiment": ("design", "run", "track", "compare", "promote", "archive"),
    "label": ("assign", "review", "correct", "merge", "map", "validate"),
    "featurestore": ("publish", "materialize", "backfill", "serve", "monitor", "deprecate"),
    "testcase": ("define", "execute", "assert", "parameterize", "isolate", "stabilize"),
    "fixture": ("prepare", "seed", "reset", "load", "teardown", "reuse"),
    "baseline": ("establish", "compare", "refresh", "approve", "pin", "version"),
    "benchmark": ("run", "compare", "profile", "optimize", "track", "report"),
    "regression": ("detect", "reproduce", "triage", "fix", "verify", "prevent"),
    "coverage": ("measure", "report", "increase", "enforce", "track", "gate"),
    "runbook": ("author", "version", "execute", "review", "validate", "retire"),
    "playbook": ("draft", "execute", "simulate", "update", "review", "publish"),
    "auditlog": ("capture", "append", "seal", "query", "retain", "export"),
    "control": ("define", "implement", "test", "enforce", "monitor", "audit"),
    "evidence": ("collect", "attach", "review", "retain", "export", "verify"),
    "finding": ("record", "triage", "assign", "remediate", "verify", "close"),
    "lineage": ("capture", "trace", "visualize", "validate", "repair", "publish"),
    "compliance": ("assess", "monitor", "report", "attest", "remediate", "enforce"),
}
