# SPDX-License-Identifier: BUSL-1.1
# Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four
# years from publication; Change License: Apache-2.0
# Copyright (c) 2026 Empower Agile
"""Generated data (byte-identical to Java RoleSuffixDictionary). Do not edit by hand."""

DESIGN_PATTERN_SUFFIXES = (
    "service",
    "repository",
    "controller",
    "factory",
    "builder",
    "strategy",
    "observer",
    "adapter",
    "decorator",
    "visitor",
    "command",
    "facade",
    "proxy",
    "gateway",
    "client",
)

FUNCTIONAL_SUFFIXES = (
    "validator",
    "converter",
    "mapper",
    "resolver",
    "provider",
    "listener",
    "interceptor",
    "filter",
    "scheduler",
    "dispatcher",
    "router",
    "registry",
    "store",
    "cache",
    "engine",
    "renderer",
    "executor",
    "analyzer",
    "scanner",
    "parser",
    "formatter",
    "encoder",
    "decoder",
    "serializer",
    "loader",
    "exporter",
    "importer",
    "inspector",
    "monitor",
    "notifier",
    "publisher",
    "consumer",
    "producer",
    "transformer",
    "translator",
    "generator",
    "authenticator",
    "authorizer",
    "coordinator",
    "aggregator",
    "orchestrator",
    "middleware",
    "evaluator",
    "ranker",
    "reranker",
    "normalizer",
    "enricher",
    "redactor",
    "guard",
    "policy",
)

GENERIC_SUFFIXES = (
    "manager",
    "handler",
    "processor",
    "helper",
    "utility",
    "utils",
    "util",
    "common",
    "base",
    "default",
    "data",
    "info",
    "impl",
)

# role suffix -> ordered expected verbs
EXPECTED_VERBS = {
    "repository": ("find", "save", "delete", "exists", "count", "get"),
    "factory": ("create", "build", "make", "of", "from", "new"),
    "builder": ("create", "build", "make", "of", "from", "with", "set", "add"),
    "validator": ("validate", "check", "verify", "ensure", "is"),
    "converter": ("convert", "transform", "map", "to", "from"),
    "mapper": ("map", "convert", "transform", "to", "from"),
    "parser": ("parse", "read", "extract", "tokenize"),
    "formatter": ("format", "render", "display", "print"),
    "renderer": ("render", "display", "format", "draw"),
    "scheduler": ("schedule", "cancel", "reschedule", "delay"),
    "dispatcher": ("dispatch", "send", "route", "forward"),
    "filter": ("filter", "accept", "reject", "matches", "test"),
    "listener": ("on", "handle", "receive", "process"),
    "orchestrator": ("start", "advance", "pause", "resume", "cancel", "complete"),
    "middleware": ("intercept", "wrap", "authorize", "validate", "forward"),
    "evaluator": ("evaluate", "score", "compare", "rank"),
    "ranker": ("rank", "score", "sort", "rerank"),
    "reranker": ("rerank", "score", "sort", "rank"),
    "normalizer": ("normalize", "standardize", "cleanse", "transform"),
    "enricher": ("enrich", "augment", "hydrate", "join"),
    "redactor": ("redact", "sanitize", "mask", "scrub"),
    "guard": ("validate", "enforce", "block", "allow"),
    "policy": ("evaluate", "enforce", "apply", "override"),
    "controller": ("create", "read", "update", "delete", "list", "get", "find", "save"),
    "service": (),
    "gateway": ("send", "receive", "connect", "disconnect", "forward"),
    "cache": ("get", "put", "evict", "invalidate", "contains", "clear"),
    "store": ("get", "put", "save", "delete", "find", "contains", "clear"),
    "registry": ("register", "unregister", "lookup", "find", "get", "contains"),
}
