# SPDX-License-Identifier: BUSL-1.1
# Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four
# years from publication; Change License: Apache-2.0
# Copyright (c) 2026 Empower Agile
"""The promotion-matrix renderer: ``packages/narrativetrace-skills/ledger/promotion.md`` is
regenerated from ``ledger/runs.jsonl`` — never hand-edited; drift fails ``poe check``'s
``promotion-check`` task (``promotion-render`` fixes it). Mirrors ``scripts/skills_render.py``'s
own drift-check discipline for the SKILL.md/AGENTS.md build output.
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from narrativetrace_skills import SKILLS
from scripts.translation_check import REPO_ROOT

_LEDGER_DIR = REPO_ROOT / "packages" / "narrativetrace-skills" / "ledger"
_RUNS_PATH = _LEDGER_DIR / "runs.jsonl"
_PROMOTION_PATH = _LEDGER_DIR / "promotion.md"

_PLATFORM_COLUMNS = (("claude", "Claude"), ("codex", "Codex"), ("gemini", "Gemini"))


@dataclass(frozen=True, slots=True)
class LedgerRow:
    date: str
    skill: str
    case: str
    platform: str
    model: str
    trial: int
    result: str


def parse_runs_jsonl(content: str) -> tuple[LedgerRow, ...]:
    """One JSON object per non-blank line, the shape a Tier B runner's ``run.py`` writes."""
    rows = []
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        payload = json.loads(stripped)
        rows.append(
            LedgerRow(
                date=payload["date"],
                skill=payload["skill"],
                case=payload["case"],
                platform=payload["platform"],
                model=payload["model"],
                trial=payload["trial"],
                result=payload["result"],
            )
        )
    return tuple(rows)


def _rows_for(runs: tuple[LedgerRow, ...], skill: str, platform: str) -> tuple[LedgerRow, ...]:
    return tuple(row for row in runs if row.skill == skill and row.platform == platform)


def _is_approved(rows: tuple[LedgerRow, ...]) -> bool:
    """Promotion state: "one green trigger sample + green happy-path"."""

    def _green(needle: str) -> bool:
        return any(needle in row.case and row.result == "pass" for row in rows)

    return _green("happy-path") and _green("trigger")


def _cell_for(runs: tuple[LedgerRow, ...], skill: str, platform: str) -> str:
    rows = _rows_for(runs, skill, platform)
    if not rows:
        return "not yet run"
    if _is_approved(rows):
        return "approved"
    latest = rows[-1]
    date = latest.date[:10]
    return (
        f"green ({latest.model}, {date})"
        if latest.result == "pass"
        else f"red ({latest.model}, {date})"
    )


_HEADER = """# Promotion matrix

Skill x platform. A cell turns **approved** after one green trigger sample and one green
happy-path case on that platform; **green (model, date)** marks the most recent passing trial;
**red (model, date)** marks the most recent failing one; **not yet run** means no trial has landed
a row in `ledger/runs.jsonl` for that pair yet. An empty or non-approved cell never blocks the
nightly -- only the Claude lane's own green gates shipping (`evals/README.md`'s sporadic policy)
-- but it blocks that skill's promotion to fully-approved status. A wording or fixture change
clears that skill's row; re-approval accrues again from `ledger/runs.jsonl`.

Regenerated by `scripts/promotion_render.py` from `ledger/runs.jsonl` -- never hand-edited; drift
fails `poe check` (`python scripts/promotion_render.py --check`; `--fix` fixes it).
"""


def render_promotion_markdown(skill_names: tuple[str, ...], runs: tuple[LedgerRow, ...]) -> str:
    """Regenerates ``ledger/promotion.md``'s full content from the typed skill catalogue and the
    ledger."""
    column_headers = " | ".join(header for _, header in _PLATFORM_COLUMNS)
    header_lines = [
        f"| Skill | {column_headers} |",
        f"|---|{'|'.join('---' for _ in _PLATFORM_COLUMNS)}|",
    ]
    rows = [
        f"| `{name}` | "
        + " | ".join(_cell_for(runs, name, platform) for platform, _ in _PLATFORM_COLUMNS)
        + " |"
        for name in skill_names
    ]
    return f"{_HEADER}\n" + "\n".join([*header_lines, *rows]) + "\n"


def _current_skill_names() -> tuple[str, ...]:
    return tuple(skill.canonical_name for skill in SKILLS)


def _expected_content() -> str:
    runs = parse_runs_jsonl(_RUNS_PATH.read_text(encoding="utf-8")) if _RUNS_PATH.is_file() else ()
    return render_promotion_markdown(_current_skill_names(), runs)


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    mode = args[0] if args else None
    if mode not in ("--check", "--fix"):
        print("Usage: python scripts/promotion_render.py --check|--fix", file=sys.stderr)
        return 1
    expected = _expected_content()
    if mode == "--check":
        actual = _PROMOTION_PATH.read_text(encoding="utf-8") if _PROMOTION_PATH.is_file() else None
        if actual != expected:
            print(
                "ledger/promotion.md does not match ledger/runs.jsonl -- run "
                "`python scripts/promotion_render.py --fix`.",
                file=sys.stderr,
            )
            return 1
        print("promotion_render: ledger/promotion.md matches ledger/runs.jsonl")
        return 0
    _PROMOTION_PATH.write_text(expected, encoding="utf-8")
    print(f"wrote {_PROMOTION_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
